### PR TITLE
Big big changes around here, please have a look

### PR DESCRIPTION
**Pull request by Jackosan6**

### CODE REVIEW

**Comment by rosseji** [comment]
Am sad.. was wanting to try it out but I'm no longer on the ysi dropbox... (which is having major outages btw)

**Comment by Jackosan6** [comment]
We should make it non-dropbox friendly in the future.

#codegoals

**Comment by rosseji** [comment]
That could be cool. Cause it's just pulling down ABS sheets and viewing them right?

**Comment by rosseji** [comment]
If I remember correctly it was storing on dropbox so that people to access previously downloaded series?

**Comment by Jackosan6** [comment]
At the moment it's just pulling from what has already been downloaded to Dropbox, to a specific folder with the data you might need to look at a topic.
Connecting with websites when loading each time has been sidelined for the moment.

**Comment by rosseji** [comment]
Cool cool cool. If you want to email mail me the files in the folder I'd be able to test out the package?

**Pull request merged**
